env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
sudo: false
language: node_js
node_js:
- '0.12'
script: npm test
before_install:
- openssl aes-256-cbc -K $encrypted_15e469258d4f_key -iv $encrypted_15e469258d4f_iv
  -in task-graph-scheduler.conf.json.enc -out task-graph-scheduler.conf.json -d

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "im55C6cvGkzcMuIt+kjjr54+vmPBPWDk2ZAo0s7OdOw34I584mS13Mi62kLR3xVECA1a+TeRAqUE8nzd9az0bBwt7mq+s1qkJAkPKf7M3sQMGRzpFoH7hjwwDApyoT+ESC/L8KONm/Hic9koj2n77WOx2RF5Q7rnghLLtjOubSA="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
